### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by lk77** [Askedio/laravel-soft-cascade#100]
Hello,

laravel 6.0 is out now,

do you plan to support it ?

thanks.

**Comment by maguilar92** [comment]
@lk77 Yes, could you do PR with the necessary changes for laravel 6.

If not, in a few days I will try to have it.

**Comment by lk77** [comment]
thanks,

I will wait a few days, i don't know the package well enough to make changes to it ^^

i've used "6.0 as 5.8" in the constraint for now, just for testing out the new version.

**Comment by maguilar92** [comment]
Great!

**Comment by maguilar92** [comment]
Closed, https://github.com/Askedio/laravel-soft-cascade/pull/102 will be merged

**Comment by lk77** [comment]
ok, thanks.
