### ISSUE TITLE
6.0 isnt available via Composer

### ISSUE THREAD

**Issue by j-fulbright** [Askedio/laravel-soft-cascade#103]
It appears that 6.0 isn't available via Composer currently

**Comment by Lloople** [comment]
As far as I know, they are having [some trouble](https://github.com/Askedio/laravel-soft-cascade/pull/102#issuecomment-529216989) since GitHub changed the Services workflow. I think this modification can only be done by the repository owner @gcphost 🙁

**Comment by gcphost** [comment]
@byteasc @Lloople I have updated the integration for Packagist and 6.0 is now available.
