### ISSUE TITLE
Cascading forceDelete

### ISSUE THREAD

**Issue by invaders-xx** [Askedio/laravel-soft-cascade#108]
- Laravel Soft Cascade Version: 5.7
- PHP Version: 7.3
- Database Driver & Version: mysql 5.7

### Description:
Is there any way to forceDelete cascade with this package ? I mean I have several model using SoftDelete and your very useful package but I would also like to be able to forceDelete and cascadin forceDelete on Relations.
Many thanks in advance for your answer.

**Comment by maguilar92** [comment]
@invaders-xx Mysql does it when you define the foreign key with ON DELETE CASCADE.
