### ISSUE TITLE
Doesn't support Laravel Tinker 2.0

### ISSUE THREAD

**Issue by SuperDJ** [Askedio/laravel-soft-cascade#110]
- Laravel version: 6.6.1
- Laravel Soft Cascade Version: 6.0.0
- PHP Version: 7.3
- Database Driver & Version: MySQL

### Description:
Laravel Tinker 2.0 isn't supported.

### Steps To Reproduce:
Update Laravel Tinker to version 2.0 and you'll get an error message.

**Comment by maguilar92** [comment]
This package doesn't have laravel tinker as package dependency and is not using it. Must be a problem on your project dependencies.
