### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by BoyeMagnus** [Askedio/laravel-soft-cascade#112]

**Comment by nessimabadi** [comment]
laravel-shift

**Comment by maguilar92** [comment]
@nessimabadi laravel-shift is a payment upgrade service.

**Comment by maguilar92** [comment]
@BoyeMagnus Laravel 7 support will be added in the next days

**Comment by kohlerdominik** [comment]
@maguilar92 how's the progress? Is there a lot to do?

**Comment by hassanrazadev** [comment]
When will we get support for Laravel 7?

**Comment by maguilar92** [comment]
Yes, I do not have time actually. You could create a pull request with upgrade changes or wait.

I will attempt to do it today.

**Comment by hassanrazadev** [comment]
@maguilar92 thanks

**Comment by maguilar92** [comment]
Support to laravel 7 added on release 7.0.0 😄
