### ISSUE TITLE
Compatible with laravel-auditing

### ISSUE THREAD

**Issue by cmayorgahilario** [Askedio/laravel-soft-cascade#115]
- Laravel version: 7.10.3
- Laravel Soft Cascade Version: 7.0.0
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
does not record auditable

### Steps To Reproduce:
Install owen-it/laravel-auditing:10.0.0
Create Subject -> Topic 
Delete Subject, only record auditable data for Subject no for Topic and similar for forceDeleted

**Comment by maguilar92** [comment]
@DevMakoto I think that it is related to: https://github.com/Askedio/laravel-soft-cascade/issues/90

If you want you are free to submit a pull request for this fix. At now I do not have time for implement it.
