### ISSUE TITLE
What if onDelete is restrict instead of cascade?

### ISSUE THREAD

**Issue by rohanvakharia** [Askedio/laravel-soft-cascade#12]
What will happen if I have used onDelete restrict while creating a relationship. Does this softDelete will raise and restrict that record from softdeleting?

**Comment by gcphost** [comment]
Hi

There is no support for restrict deleting tho I do hope to add it, another array to restrict deletes would be the idea.

https://github.com/Askedio/laravel5-soft-cascade/blob/master/src/SoftCascade.php#L8

**Comment by rohanvakharia** [comment]
@gcphost Thanks for considering it is as enhancement. Great, you have that in your to-do list.

**Comment by maguilar92** [comment]
@gcphost @rohanvakharia I added support to restricted relations as you can see on #24 

Will be available soon

Enjoy it :)

**Comment by gcphost** [comment]
Sent out just now as a pre-release, will release shortly.

**Comment by maguilar92** [comment]
Perfect 👍

**Comment by rohanvakharia** [comment]
Thanks @maguilar92 and @gcphost

**Comment by maguilar92** [comment]
@gcphost This issue is solved, you will close it? Thanks

**Comment by gcphost** [comment]
You're welcome
