### ISSUE TITLE
There is no license information available / No license reference in composer.json

### ISSUE THREAD

**Issue by perstnev** [Askedio/laravel-soft-cascade#125]
- Laravel Soft Cascade Version: 7.0.2-8.1.0

### Description:
BlackDuck software highlights laravel-soft-cascade as library with unknown license.
Same is reported by packagist.org ("There is no license information available for the latest version (8.1.0) of this package.")

### Steps To Reproduce:
Visit packagist repository of the package:
https://packagist.org/packages/askedio/laravel-soft-cascade#7.0.2
https://packagist.org/packages/askedio/laravel-soft-cascade 

### Solution:
According to https://getcomposer.org/doc/04-schema.md#license it should be added to composer.json.
{
    "license": "MIT"
}

**Comment by perstnev** [comment]
Created corresponding pull request 
https://github.com/Askedio/laravel-soft-cascade/pull/126
if you don't mind

**Comment by maguilar92** [comment]
Merged, will be released when @gcphost give me permission in organization to fix travis & codacy integration.
