### ISSUE TITLE
Doesn't cascade with query deletes

### ISSUE THREAD

**Issue by matt-allan** [Askedio/laravel-soft-cascade#13]
Hello,

If you do a delete with a query like this:

``` php
User::whereId(1)->delete();
```

Eloquent will perform the soft delete but doesn't trigger an event.  [Taylor said that's expected behavior](https://github.com/laravel/framework/issues/2536#issuecomment-140449715), so that probably won't be fixed.  That means the cascade will not work for query deletes.

Here is a failing test that illustrates the problem:

``` php
public function testDeleteWhenQuery()
    {
        $this->createUserRaw();
        $this->createUserRaw();

        User::whereId(1)->delete();

        $this->assertEquals(2, User::withTrashed()->count());
        $this->assertEquals(1, User::count());

        $this->assertEquals(2, Profiles::withTrashed()->count());
        $this->assertEquals(1, Profiles::count(), 'The delete should cascade');
    }
```

If you look at [how Laravel does it for the primary model](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/SoftDeletingScope.php#L38), they register a callback with the Builder.  It seems like hooking in there would allow cascading on queries too.

**Comment by gcphost** [comment]
Thank you, I will investigate this further.

**Comment by AngelinCalu** [comment]
same issue with:
```
User::whereId(1)->restore();
```

as an alternative I am using:
```
User::findOrFail(1)->delete();

and

User::findOrFail(1)->restore();
```

**Comment by gcphost** [comment]
This PR allows you to use the query builder:

https://github.com/Askedio/laravel5-soft-cascade/pull/22#pullrequestreview-34893283

I've sent it to master, just need to release.
