### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by seabasss** [Askedio/laravel-soft-cascade#136]
I see a closed topic about Laravel 9 support, but this package is the only one not letting me update to Laravel 9.

Here's the error:
```
  Problem 1
    - Root composer.json requires askedio/laravel-soft-cascade ^8.1 -> satisfiable by askedio/laravel-soft-cascade[8.1.0].
    - askedio/laravel-soft-cascade 8.1.0 requires illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require askedio/laravel-soft-cascade:*" to figure out if any version is installable, or "composer require askedio/laravel-soft-cascade:^2.1" if you know which you need.
```

Any ideas? Thanks!

**Comment by RhysLees** [comment]
You can use `composer require askedio/laravel-soft-cascade:master` for now until a release tag is made

USE AT YOUR OWN RISK

by using this any time you update it will pull the master branch which may not be stable

**Comment by invaders-xx** [comment]
When do you plan to release for L9 please ?

**Comment by SteveSzumski** [comment]
Would love to see Laravel 9 support for this package!

**Comment by RhysLees** [comment]
Ayy we just got a release for L9 https://github.com/Askedio/laravel-soft-cascade/releases/tag/9.0.0
