### ISSUE TITLE
Status of this package

### ISSUE THREAD

**Issue by RhysLees** [Askedio/laravel-soft-cascade#137]
On the 15th of February, Laravel 9 support was merged with #131 but no release was ever made.
An issue was raised with the request to make a release tag #136 but it has gone un responded.

Is this package now considered abandoned? 
4 months later no release has been created forcing users to either use the main branch which isn't the best or find an alternate package.

**Comment by gcphost** [comment]
How is the main branch working out? I can tag it for release

**Comment by RhysLees** [comment]
> How is the main branch working out? I can tag it for release

It's worked fine fine February. It's jsut missing the release from the L9 support merge

**Comment by gcphost** [comment]
Sorry it's been a while since I've had to do a release, but I made one here:
https://github.com/Askedio/laravel-soft-cascade/releases/tag/9.0.0

**Comment by gcphost** [comment]
On a side note if @maguilar92 is too busy [as I am] we are open for new maintainers! This a popular soft cascade package for laravel with over 700k installs, I'd like to keep it going :D

**Comment by RhysLees** [comment]
> Sorry it's been a while since I've had to do a release, but I made one here: https://github.com/Askedio/laravel-soft-cascade/releases/tag/9.0.0

You're a legend! thank you!

**Comment by RhysLees** [comment]
> On a side note if @maguilar92 is too busy [as I am] we are open for new maintainers! This a popular soft cascade package for laravel with over 700k installs, I'd like to keep it going :D

Same here, been flat out and I have too many side projects as is but it would be awesome if someone would be willing to be added as a maintainer
