### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by BernhardK91** [Askedio/laravel-soft-cascade#138]
Laravel 10 was released this week, so Laravel 10 support should be added.

**Comment by BernhardK91** [comment]
I wanted to make a PR, but the test `IntegrationTest::testDeleteQueryBuilder()` failed on my machine and I do not understand the package well enough to fix that by myself. Sorry.

**Comment by maguilar92** [comment]
Now it's added at version [10.0.0](https://github.com/Askedio/laravel-soft-cascade/releases/tag/10.0.0)
