### ISSUE TITLE
Problems with Laravels many-to-many relationship

### ISSUE THREAD

**Issue by aglavas** [Askedio/laravel-soft-cascade#19]
If we define many-to-many relationship, for example User-Roles. Trait will not set soft delete timestamp on pivot table, instead exception will be thrown with message that updated_at column is ambigious. Probably because both roles and user_roles table has updated_at field.

It happens only on many-to-many relationships. I made workaround for this, and that is defining relation just for softDelete. So in the end it looks like this:

```
public function role()
    {
        return $this->belongsToMany(Role::class, 'user_role', 'user_id','role_id')->withTimestamps();
    }

    public function role_soft_delete()
    {
        return $this->hasMany(UserRole::class, 'user_id', 'id');
    }

protected $softCascade = ['meal_soft_delete'];
```

Using this workaround it works normally.

**Comment by maguilar92** [comment]
@mrgarbage @gcphost  In a short time there will be support as soon as the pull request is raised

**Comment by gcphost** [comment]
Release updated.

Thank you.

**Comment by Thirdwrist** [comment]
His this been fixed, I Seem to be having the same issues for 5.8, I will use the workaround that should work, but it does not do so straight ahead without the workaround...

**Comment by FranciscoCaldeira** [comment]
Same problem 2022
