### ISSUE TITLE
getting errors

### ISSUE THREAD

**Issue by eduarguz** [Askedio/laravel-soft-cascade#26]
any idea why am i getting this error? 
`PHP error:  Undefined index: class in /**/vendor/askedio/laravel5-soft-cascade/src/Listeners/CascadeQueryListener.php on line 20`

**Comment by eduarguz** [comment]
one of the calls that makes this error is:
```
2 => array:4 [
      "file" => "/Users/eguzman/Documents/4bh/4BuyHub/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php"
      "line" => 367
      "function" => "call_user_func_array"
      "args" => array:2 [
        0 => array:2 [
          0 => Askedio\SoftCascade\Listeners\CascadeQueryListener {#856}
          1 => "handle"
        ]
        1 => array:1 [
          0 => Illuminate\Database\Events\QueryExecuted {#844}
        ]
      ]
    ]
```
because there is no `class` index 
any idea why?

**Comment by maguilar92** [comment]
We need more information. 

What version of laravel and php are you using?

Thank you.

**Comment by maguilar92** [comment]
I made a pull request with the code that should solve your problem.
#27

**Comment by gcphost** [comment]
Thanks @maguilar92 , pr merged.

**Comment by eduarguz** [comment]
Thank you guys, everything is ok now
