### ISSUE TITLE
Will it be updated to Laravel 5.5 

### ISSUE THREAD

**Issue by eduarguz** [Askedio/laravel-soft-cascade#34]
I would like to update an existing app, but, i dont really know what is the process for checking L5.5 compatibility.
If you don't have time for that, could you give me an idea of how to help you?

**Comment by maguilar92** [comment]
It will be updated when lumen-framework version 5.5 comes out.

**Comment by maguilar92** [comment]
Updated to work with laravel and lumen 5.5 released.
