### ISSUE TITLE
Having a problem making the package work

### ISSUE THREAD

**Issue by savamarkovic** [Askedio/laravel-soft-cascade#42]
Hey.
I really like the idea of the package and tried using it but I stubmled upon the issue where when I try and soft delete an object I get the following error:
`ErrorException in CascadeDeleteListener.php line 18:
Missing argument 2 for Askedio\SoftCascade\Listeners\CascadeDeleteListener::handle()`

Here is part of the stack trace:

> in CascadeDeleteListener.php line 18
> at HandleExceptions->handleError('2', 'Missing argument 2 for Askedio\SoftCascade\Listeners\CascadeDeleteListener::handle()', '/var/www/html/arabian/vendor/askedio/laravel5-soft-cascade/src/Listeners/CascadeDeleteListener.php', '18', array('event' => object(Pilot))) in CascadeDeleteListener.php line 18
> at CascadeDeleteListener->handle(object(Pilot))
> at call_user_func_array(array(object(CascadeDeleteListener), 'handle'), array(object(Pilot))) in Dispatcher.php line 349
> at Dispatcher->Illuminate\Events\{closure}(object(Pilot))
> at call_user_func_array(object(Closure), array(object(Pilot))) in Dispatcher.php line 221
> at Dispatcher->fire('eloquent.deleting: App\Pilot', object(Pilot), true) in Dispatcher.php line 164
> at Dispatcher->until('eloquent.deleting: App\Pilot', object(Pilot)) in Model.php line 1663
> at Model->fireModelEvent('deleting') in Model.php line 1104
> at Model->delete(array()) in EntrustUserTrait.php line 34
> at Pilot->delete() in PilotController.php line 220
> at PilotController->destroy('1089')
> at call_user_func_array(array(object(PilotController), 'destroy'), array('pilot' => '1089')) in Controller.php line 55
> at Controller->callAction('destroy', array('pilot' => '1089')) in ControllerDispatcher.php line 44
> at ControllerDispatcher->dispatch(object(Route), object(PilotController), 'destroy') in Route.php line 190

I have the deleted_at columns in both tables and here are the models.
Pilot.php
```

<?php

namespace App;

use Cmgmyr\Messenger\Traits\Messagable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Venturecraft\Revisionable\RevisionableTrait;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use \Askedio\SoftCascade\Traits\SoftCascadeTrait;

class Pilot extends Authenticatable {

    use SoftDeletes, Notifiable, EntrustUserTrait, RevisionableTrait, Messagable, SoftCascadeTrait {
        SoftDeletes::restore insteadof EntrustUserTrait;
    }

    protected $softCascade = ['pireps'];
    protected $table = 'pilots';
   #### ..........
    public function pireps () {
        return $this->hasMany(PIREP::class);
    }

```

PIREP.php
```

<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Askedio\SoftCascade\Traits\SoftCascadeTrait;

class PIREP extends Model {

    use SoftDeletes, SoftCascadeTrait; 

    public function pilot () {
        return $this->belongsTo(Pilot::class);
    }
```

How I am trying to delete the Pilot object (and the associated PIREPs)

```
PilotController.php

    public function destroy($id) {
        $pilot = Pilot::findOrFail($id);
        if (!$pilot) {
            Flash::error('There is no pilot with that ID.');
            return redirect()->back();
        }
        $pilot->delete();
        Flash::success('The pilot has been deleted.');
        return redirect()->route('admin.pilots.index');
    }
```

Can you provide some ideas?
To add, it seems when I tried to revert back and delete everything from the model that has to do with the package I still get the error upon trying to delete, even though I didn't specify $softCascade or have the use SoftCascadeTrait. Only after I comment out the provider from app.php the error stops displaying.

**Comment by maguilar92** [comment]
Hello @savamarkovic,
I need if you are using laravel/lumen with what version and Askedio/laravel5-soft-cascade version.

Thanks :)

**Comment by guigofu** [comment]
Hello, 
I am experiencing the same behavior ,working with: laravel version 5.2.45, Askedio/laravel5-soft-cascade version 5.5.5

**Comment by maguilar92** [comment]
This package version only works for laravel 5.5.*.

To use with Laravel 5.2.45 yo need to use Askedio/laravel5-soft-cascade version 1.8.

As I can see in composer.json laravel 5.5.5 is on require-dev. I will fix it to next release!

Thanks :)
