### ISSUE TITLE
5.5 Breaking changes

### ISSUE THREAD

**Issue by gcphost** [Askedio/laravel-soft-cascade#48]
https://github.com/laravel/framework/issues/20869#issuecomment-326334760

Need to rename variables to support 5.5 changes.

**Comment by gcphost** [comment]
Need to use `getQualifiedOwnerKeyName` on a BelongsTo and `getQualifiedForeignKeyName` on a HasManyThrough

**Comment by gcphost** [comment]
I added `getForeignKeyUse` but this is undesirable.

```
$foreignKeyUse = $this->getForeignKeyUse($modelRelation);
            $foreignKeyIdsUse = $foreignKeyIds;

            //Many to many relations need to get related ids and related local key
            if ($modelRelation instanceof BelongsToMany) {
                extract($this->getBelongsToManyData($modelRelation, $foreignKeyIds));
            } elseif ($modelRelation instanceof MorphOneOrMany) {
                extract($this->getMorphManyData($modelRelation, $foreignKeyIds));
            }
```

Needs to be refactored to remove elseif and we can define the fk instead of testing to get it before. the relations instanceof checks.

**Comment by maguilar92** [comment]
Sorry still fails in methods getBelongsToManyData and getMorphManyData

**Comment by maguilar92** [comment]
Now is solved :=)
