### ISSUE TITLE
Does it work for laravel 5.2.30?

### ISSUE THREAD

**Issue by coding-sunshine** [Askedio/laravel-soft-cascade#5]
I am trying to install it on 5.2.30 but doesn't let me

**Comment by gcphost** [comment]
Hi

I am deving on 5.2.30 and it updated composer to require 5.1.\* due to a fork I saw that only changed that. (v5.2.31 now)

Try

```
composer require askedio/laravel5-soft-cascade:1.1
```

Otherwise report the error.
