### ISSUE TITLE
Missing 2nd Argument

### ISSUE THREAD

**Issue by kenegade** [Askedio/laravel-soft-cascade#56]
ErrorException in CascadeDeleteListener.php line 18:
Missing argument 2 for Askedio\SoftCascade\Listeners\CascadeDeleteListener::handle()

I'm getting the error above when deleting a model.   In debugging, I've removed all the items in the $softCascade array, so I don't think it's a Model code issue, but who knows.

I'm Laravel 5.3.  Need more info?

**Comment by maguilar92** [comment]
See #42

To use with Laravel 5.3 you need to use Askedio/laravel5-soft-cascade version 1.8.

**Comment by kenegade** [comment]
That worked perfectly sorry for the duplicated error.  I didn't see how to review closed issues, but now I do.  Thanks for the uber quick response!

**Comment by maguilar92** [comment]
You're welcome and thanks!!
