### ISSUE TITLE
Change package name from laravel5-soft-cascade to laravel-soft-cascade 

### ISSUE THREAD

**Issue by maguilar92** [Askedio/laravel-soft-cascade#58]
@gcphost I think it would be nice to rename the package from laravel5-soft-cascade to laravel-soft-cascade.

It's just a proposal.

**Comment by gcphost** [comment]
I agree.

**Comment by gcphost** [comment]
Done. Hopefully there are no issues.

**Comment by maguilar92** [comment]
Perfect!! I will make now the package to follow the laravel lifecycle os terms of support.

Thanks!!
