### ISSUE TITLE
Bad pivot key name used on BelongsToMany relation

### ISSUE THREAD

**Issue by squiaios** [Askedio/laravel-soft-cascade#61]
On belongs to many relation, a bad pivot key name is used to find the good relation

https://github.com/Askedio/laravel5-soft-cascade/blob/d0424664f3f1e0b9a0c823cf1d2cf6bd00884e6d/src/SoftCascade.php#L146

Changing `getQualifiedForeignPivotKeyName` with `getRelatedPivotKeyName` works for me :)

**Comment by maguilar92** [comment]
Hello @squiaios 
Can you post the error and the related models to check your error?

Thank you

**Comment by squiaios** [comment]
I have no PHP / eloquent error

**Class Foo**
[Foo.txt](https://github.com/Askedio/laravel5-soft-cascade/files/1914363/Foo.txt)

**Class Bar**
[Bar.txt](https://github.com/Askedio/laravel5-soft-cascade/files/1914362/Bar.txt)

**Migrations**
[2018_04_15_000000_create_foos_table.txt](https://github.com/Askedio/laravel5-soft-cascade/files/1914373/2018_04_15_000000_create_foos_table.txt)
[2018_04_16_000000_create_bars_table.txt](https://github.com/Askedio/laravel5-soft-cascade/files/1914374/2018_04_16_000000_create_bars_table.txt)
[2018_04_17_160000_create_bar_foo_table.txt](https://github.com/Askedio/laravel5-soft-cascade/files/1914375/2018_04_17_160000_create_bar_foo_table.txt)

**Seeder**
[FooBarSeeder.txt](https://github.com/Askedio/laravel5-soft-cascade/files/1914378/FooBarSeeder.txt)

**Tinker**
`App\Models\Foo::find(16)->delete();`

**Comment by squiaios** [comment]
Is it possible to make this fix available on laravel 5.5 please :)

**Comment by maguilar92** [comment]
@squiaios 
Yes, I will do it.
I will check package maintenance to follow laravel version standards.

**Comment by squiaios** [comment]
oh perfect, thank you =D

**Comment by maguilar92** [comment]
@gcphost Can you create or add me roles for create:
5.5 branch with 5.5.13 version code
5.6 branch with master branch code

With this branches I will make package maintenance to follow laravel versions lifecycle.

**Comment by gcphost** [comment]
Permissions updated @maguilar92 , you should be able to do this now.

**Comment by maguilar92** [comment]
@gcphost I can't still create branches.

<img width="1023" alt="captura de pantalla 2018-04-21 a las 18 59 32" src="https://user-images.githubusercontent.com/25102127/39086697-28b71054-4596-11e8-85c3-8926801b1f95.png">

**Comment by gcphost** [comment]
Weird, I thought as an admin you'd get to do that.

I've created both branches. Let me know if I've done something wrong.

**Comment by maguilar92** [comment]
@squiaios Available now at version 5.5.14. 
You must change dependency name in composer.json from askedio/laravel5-soft-cascade to askedio/laravel-soft-cascade

**Comment by squiaios** [comment]
perfect, thank you :)
