### ISSUE TITLE
Support query builder

### ISSUE THREAD

**Issue by gcphost** [Askedio/laravel-soft-cascade#67]
I ran across this in a comment earlier:

https://github.com/jarektkaczyk/eloquent-cascade/

It would be nice if we can support the QB too, if we don't already.

**Comment by maguilar92** [comment]
We support query builder, the section of readme.md is:

It can also be used with query builder in this way because query builder listener is executed after query, we need to use transaction for rollback query on error due to restricted relationships

**Comment by gcphost** [comment]
Oh forgive me for not reading the manual :(

**Comment by maguilar92** [comment]
Hehehe no problem!! We have the most complete package @gcphost
