### ISSUE TITLE
Cascading does not work with pivot tables?

### ISSUE THREAD

**Issue by thafnyy** [Askedio/laravel-soft-cascade#79]
I am using laravel 5.4 and need to perform a soft delete through a pivot table, ie I have a pivot table which, when deleted, needs to cascade the delete to another table.
When executing 'delete', the pivot table is 'deleted', but nothing happens to the other table. Any idea?

table that will have the cascaded delete:
`protected $softCascade = ['category'];`

delete statement
`CompanyService::findOrFail(11)->delete();`

NOTE: In my migrations I did not use onCascade, is this a problem?

Thank you in advance and sorry for my English.

**Comment by maguilar92** [comment]
Hi @thafnysoares.

Laravel 5.4 is no longer supported and will not receive updates of any kind as our package. I recommend upgrading to laravel 5.5 or higher.

Thanks!
