### ISSUE TITLE
For models that are not using SoftDeletes

### ISSUE THREAD

**Issue by abhimanyu003** [Askedio/laravel-soft-cascade#8]
This is really nice package, makes life lot easier.

It will be great if also supports models that are not using SoftDeletes

There are many situations where you don't like to use `SoftDeletes` for example 

Blogs `hasMany` Comments. 
( We are not using SoftDeletes on `comments` table )

Right now it throws this exception.

``` php
Illuminate\Database\Query\Builder::withTrashed()
```

If Update https://github.com/Askedio/laravel5-soft-cascade/blob/master/src/SoftCascade.php#L90 to

``` php
foreach ($relation->get() as $model) {
```

this resolves the issue, but i'm looking forward to your solution.

Thanks

**Comment by gcphost** [comment]
Thanks for the issue.

Sounds like withTrashed() is bogus if soft deletes isn't enabled, I'll play around with it on Monday.

**Comment by gcphost** [comment]
I see you made a PR, that's awesome - thank you.
