### ISSUE TITLE
Cannot delete relation with composite keys

### ISSUE THREAD

**Issue by Meshz** [Askedio/laravel-soft-cascade#82]
Hello,

First of all, thank you for this package. I'm getting an error when I try to soft delete a relation that has a composite keys. I'm using [this trait](https://gist.github.com/mpociot/121515395d48b0cffcf4ac9ea26683fc) for composite keys.

The returned error is: "_stripos() expects parameter 1 to be string, array given_". That's because in my model my primary key looks like: `protected $primaryKey = [ 'column1', 'column2' ];`. Therefore it isn't a string but an array.

Any idea on how to resolve this? Thanks for your feedback!

**Comment by maguilar92** [comment]
Eloquent doesn't support composite primary keys and our package neither do we.

The only option that I can give you is that you create a fork of our package and add that functionality. When we go making changes you can do a rebase, resolve conflicts and get the changes that we apply.

Sorry for the inconvenience.
