### ISSUE TITLE
Update to L5.7

### ISSUE THREAD

**Issue by rjsworking** [Askedio/laravel-soft-cascade#84]
Hi. 
Cannot install this package on L5.7 due to composer requirements "5.6.*".

Can you update to L5.7?

Thanks in advance

**Comment by maguilar92** [comment]
The package will be updated soon.

**Comment by rjsworking** [comment]
Thank you very much

**Comment by kentdahl** [comment]
I just tried `composer update` setting laravel to 5.7 and was surprised to see this in my composer.lock - it seems it downgraded this package in the process:

```
            "name": "askedio/laravel-soft-cascade",
-           "version": "5.6.5",
+           "version": "5.6.3",
```

Mentioning it in case it catches anyone else off-guard. 

I guess I should hold off on the upgrade until an official 5.7 version of this package is available? Or should 5.6.3 work in theory with Laravel 5.7?

**Comment by maguilar92** [comment]
Today I will update the package to version 5.7. I recommend you not to use 5.6.3.

**Comment by maguilar92** [comment]
@kentdahl Sorry but yesterday I did not have time, I'll try to have it today.

**Comment by kentdahl** [comment]
@maguilar92 ; no big rush on my account, as I probably won't be able to continue on my upgrade work until next week for other reasons.

**Comment by maguilar92** [comment]
@kentdahl @rjsworking Package updated to 5.7 version!!
