### ISSUE TITLE
Skeleton for issues.

### ISSUE THREAD

**Issue by maguilar92** [Askedio/laravel-soft-cascade#88]
@gcphost I think we need to add an skeleton when users create new issues. It could be this information:

- Laravel Soft Cascade Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Steps To Reproduce:

**Comment by gcphost** [comment]
@maguilar92 let's toss in Laravel Version so we can replicate pretty much everything.

And maybe something about how to write code comments (based on the recent issue).

**Comment by maguilar92** [comment]
@gcphost I see it well! In what sense?

**Comment by gcphost** [comment]
In what sense about code comments? Just saying to use ``` and what not, the latest issue has pasted code without any code blocks.

**Comment by maguilar92** [comment]
Yes, I mean it would be good to add that when someone creates an issue, a skeleton comes out, such as:

- Laravel Soft Cascade Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:


### Steps To Reproduce:


### Code example:

````
Put your code here
````

**Comment by gcphost** [comment]
Ya looks good to me :D

**Comment by maguilar92** [comment]
@gcphost Template created!
