### ISSUE TITLE
Restore only cascaded relations?

### ISSUE THREAD

**Issue by fullstackfool** [Askedio/laravel-soft-cascade#92]
When a resource is restored all soft-deleted relations specified in `$softCascade = ['profiles']` are also restored.

Is there any way we get make it so the package only restores the relations who were deleted in the cascade?

How about when restoring, only relations with a matching `deleted_at` are restored? I admit this wouldn't be 100% perfect, but at the moment ALL cascading relations are restored, even ones deleted far in the past.

We could add this as a configuration, so users could set which behaviour they prefer. Happy to make a PR if you are interested in the idea

**Comment by maguilar92** [comment]
Duplicated issue, follow https://github.com/Askedio/laravel-soft-cascade/issues/81

I apologize for the delay but I have been involved with other things and I have not been able to devote time to this package. When I have time I have a pending solution.
