### ISSUE TITLE
On delete set null

### ISSUE THREAD

**Issue by ghost** [Askedio/laravel-soft-cascade#95]
Does the package have set null support? I'm trying to use it with `@setnull` but it won't work.

**Comment by maguilar92** [comment]
@RafaelCorreaQuantik What do you mean with @setnull? Can you explain what's occurs?

**Comment by ghost** [comment]
Like the restrict rule, instead of cascading soft deletes, instead it unlinks the foreign key to null.

**Comment by maguilar92** [comment]
@RafaelCorreaQuantik Null is the same that if you don't put the relationship in $softCascade.
